#===============================================================================
# Docker Compose File für die lokale Entwicklung. Startet die folgenden Dienste:
#
#  * Ein MongoDB für Hilfsanzeigen und Angebote, die im internen Container-Netz für 
#    die anderen Container unter dem Hostnamen "mongodb-hilfsanzeigen" auf dem Standardport 27017 
#    erreichbar ist.
#
#  * Ein MongoDB für Benutzer, die im internen Container-Netz für 
#    die anderen Container unter dem Hostnamen "mongodb-benutzer" auf dem Port 27016
#    erreichbar ist.
#
#  * Ein grafisches Admin-Werkzeug für Mongo der Hilfsanzeigen und Angebote, das unter http://localhost:8081
#    im Browser aufgerufen werden kann.
#
#  * Ein grafisches Admin-Werkzeug für Mongo der Benutzer, das unter http://localhost:8082
#    im Browser aufgerufen werden kann.
#
#  * Eine NodeJS-Laufzeitumgebung für Hilfsanzeigen und Angebote, in welcher der Backend-Quellcode ausgeführt
#    wird. Änderungen am Quellcode führen zu einem automatischen Neustart des
#    Services. Der REST-Webservice kann unter http://localhost:3000 aufgerufen
#    werden. Unter dem Standardport 9229 kann sich ein JavaScript-Debugger
#    (z.B. aus dem Chrome Dev Tools) verbinden.
#
#  * Eine NodeJS-Laufzeitumgebung für Beutzer, in welcher der Backend-Quellcode ausgeführt
#    wird. Änderungen am Quellcode führen zu einem automatischen Neustart des
#    Services. Der REST-Webservice kann unter http://localhost:3001 aufgerufen
#    werden. Unter dem Port 9230 kann sich ein JavaScript-Debugger
#    (z.B. aus dem Chrome Dev Tools) verbinden.
#
#  * Eine NodeJS-Laufzeitumgebung, in welcher der Frontend-Quellcode (helpinghandsapp) gebaut
#    und unter der Adresse http://localhost:8080 zum Aufruf im Browser
#    bereitgestellt wird. Auch hier führen Änderungen am Quellcode zu einem
#    automatischen Neustart, so dass lediglich im Browser die Seite neugeladen
#    werden muss.
#===============================================================================
version: "3.9"

networks:
    helpinghands_default:
    hilfsanzeigen_network:
    benutzer_network:
    helpchat_network:

services:
    # MongoDB-Datenbank Help-Chat
    mongodb-helpchat:
        container_name: MongoDB-Helpchat
        image: mongo
        restart: always
        ports:
            -   27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: dbuser
            MONGO_INITDB_ROOT_PASSWORD: dbpass
        volumes:
            - dbdatahelpchat:/data/db
            - dbconfighelpchat:/data/configdbhelpchat
        networks:
            helpchat_network:
                aliases:
                    - mongodb-helpchat

    # Admin-GUI für MongoDB Helpchat
    mongo-gui-helpchat:
        container_name: MongoGUI-Helpchat
        image: mongo-express
        restart: always
        ports:
            - 8083:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_URL: mongodb://dbuser:dbpass@mongodb-helpchat:27017/
        networks:
            helpchat_network:

    # HelpingHands-Backend (Entwicklungsmodus) Helpchat
    backend-helpchat:
        container_name: Backend-Helpchat
        depends_on:
            - mongodb-helpchat
        image: node:17-alpine
        restart: always
        environment:
            HOST: "::"
            PORT: 3002
            MONGODB: mongodb://dbuser:dbpass@mongodb-helpchat:27017/
        ports:
            - 3002:3002
            - 9231:9231
        volumes:
            - ./BackendHelpchat:/app
        working_dir: /app
        command: sh -c "npm i; npm start"
        networks:
            helpchat_network:
            helpinghands_default:



    # MongoDB-Datenbank Hilfsanzeigen
    mongodb-hilfsanzeigen:
        container_name: MongoDB-Hilfsanzeigen
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: dbuser
            MONGO_INITDB_ROOT_PASSWORD: dbpass
        volumes:
            - dbdatahilfsanzeigen:/data/db
            - dbconfighilfsanzeigen:/data/configdbbenutzer
        networks:
            hilfsanzeigen_network:
                aliases:
                    - mongodb-hilfsanzeigen

    # Admin-GUI für MongoDB Hilfsanzeigen
    mongo-gui-hilfsanzeigen:
        container_name: MongoGUI-Hilfsanzeigen
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_URL: mongodb://dbuser:dbpass@mongodb-hilfsanzeigen:27017/
        networks:
            hilfsanzeigen_network:

    # HelpingHands-Backend (Entwicklungsmodus) Hilfsanzeigen
    backend-hilfsanzeigen:
        container_name: Backend-Hilfsanzeigen
        depends_on:
            - mongodb-hilfsanzeigen
        image: node:17-alpine
        restart: always
        environment:
            HOST: "::"
            PORT: 3000
            MONGODB: mongodb://dbuser:dbpass@mongodb-hilfsanzeigen:27017/
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - ./BackendHilfsanzeigen:/app
        working_dir: /app
        command: sh -c "npm i; npm start"
        networks:
            hilfsanzeigen_network:
            helpinghands_default:

    # MongoDB-Datenbank Benutzer
    mongodb-benutzer:
        container_name: MongoDB-Benutzer
        image: mongo
        ports:
            - '27016:27017'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: dbuser
            MONGO_INITDB_ROOT_PASSWORD: dbpass
        volumes:
            - dbdatabenutzer:/data/db
            - dbconfigbenutzer:/data/configdbbenutzer
            #- ./mongodb.conf:/mongodb.conf
        #command: mongod --config /mongodb.conf
        networks:
            benutzer_network:

    # Admin-GUI für MongoDB Benutzer
    mongo-gui-benutzer:
        container_name: MongoGUI-Benutzer
        image: mongo-express
        restart: always
        ports:
            - 8082:8081
        environment:
            ME_CONFIG_MOMGODB_SERVER: mongodb-benutzer
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_URL: mongodb://dbuser:dbpass@mongodb-benutzer:27017/
        networks:
            benutzer_network:

    # HelpingHands-Backend (Entwicklungsmodus) Benutzer
    backend-benutzer:
        container_name: Backend-Benutzer
        depends_on:
            - mongodb-benutzer
        image: node:17-alpine
        restart: always
        environment:
            HOST: "::"
            PORT: 3001
            MONGODB: mongodb://dbuser:dbpass@mongodb-benutzer:27017/
        ports:
            - 3001:3001
            - 9230:9230
        volumes:
            - ./BackendBenutzer:/app
        working_dir: /app
        command: sh -c "npm i; npm start"
        networks:
            benutzer_network:
            helpinghands_default:



    # HelpingHands-Frontend (Entwicklungsmodus)
#    frontend:
#        container_name: frontend
#        build: ./Frontend/helpinghandsapp
#        volumes:
#            - './:/app'
#            - '/app/node_modules'
#        ports:
#                - 8080:8080
#        stdin_open: true
#        environment:
#            - CHOKIDAR_USEPOLLING=true
#        command: npm start



volumes:
    dbdatahilfsanzeigen:
    dbconfighilfsanzeigen:
    dbdatabenutzer:
    dbconfigbenutzer:
    dbdatahelpchat:
    dbconfighelpchat:


